{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: {{ .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    cloudName: "AzurePublicCloud"
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: azure-openai-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: cosmosdb-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: cosmosdb-primary-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: signalr-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: storage-account-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: application-insights-key
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: therapy-engage-app-secrets
    type: Opaque
    data: 
    - objectName: azure-openai-key
      key: AZURE_OPENAI_KEY
    - objectName: cosmosdb-connection-string
      key: COSMOSDB_CONNECTION_STRING
    - objectName: cosmosdb-primary-key
      key: COSMOSDB_PRIMARY_KEY
    - objectName: signalr-connection-string
      key: SIGNALR_CONNECTION_STRING
    - objectName: storage-account-key
      key: STORAGE_ACCOUNT_KEY
    - objectName: application-insights-key
      key: APPLICATION_INSIGHTS_INSTRUMENTATION_KEY
{{- end }}
