apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  labels:
    app: backend-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: { { .Values.service.targetPort | default 3001 } }
      protocol: TCP
      name: http
  selector:
    app: backend-app
