apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "backend-workload-identity" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend-app
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.tenantId | quote }}
automountServiceAccountToken: true
